/*
 * Copyright 2022 Liju Jayakumar. All Rights Reserved.
*/

/*jshint esversion: 6 */

// reCAPTCHA v3
function onSubmit(token) {
    document.getElementById("demo-form").submit();
}

function clean_up(inputText) {

    inputText = inputText.replace(/S/g, "5");
    inputText = inputText.replace(/�/g, EMPTY);
    inputText = inputText.replace(/O/gi, 0);
    inputText = inputText.replace(/l/gi, 1);
    return inputText;
}

function parse() {

    // cleanup
    let inputText = clean_up(txtInput.value);
    txtInput.value = inputText;
    txtOutput.value = EMPTY;
    txtVirtualOutput.value = EMPTY;

    // prepare
    let patterns = inputPatterns.options;

    // extract
    for (let i = 0; i < patterns.length; i++) {
        let pattern = patterns[i].value;
        const regex = new RegExp(pattern, "gm");
        let pattern_matched;

        while ((pattern_matched = regex.exec(inputText)) !== null) {
            if (pattern_matched.index === regex.lastIndex) {
                regex.lastIndex++;
            }

            pattern_matched.forEach((match) => {
                let phone_number = match
                    .replace(/ /g, EMPTY)
                    .replace(/-/g, EMPTY);
                txtOutput.value += `${phone_number}` + CR_LF;

                if (chkReplaceInput.checked) {
                    txtInput.value = txtInput.value.replace(match, "");
                }

                if (chkAutoGenerate.checked) {
                    for (let index = 0; index < 10; index++) {
                        let auto_gen_number = phone_number.slice(0, -1) + index;

                        if (auto_gen_number != phone_number) {
                            txtVirtualOutput.value += `${auto_gen_number}` + CR_LF;
                        }
                    }
                }
            });
        }
    }

    showHideDownload();

    lblResult.innerHTML = setCount(RESULT, txtOutput);
    lblAutogenerated.innerHTML = setCount(AUTO_GENERATED, txtVirtualOutput);
    notify("Done");
}

function setCount(title, control) {
    return `${title} (${getLength(control)}) Numbers`;
}

function getLength(element) {
    return element.value.split("\n").length - 1;
}

function handleFileSelect(event) {
    readFile(event.files[0]);
}

function onFileDrop(event) {

    event.preventDefault();
    readFile(event.dataTransfer.files[0]);
}

function readFile(file) {
    const reader = new FileReader();
    reader.onload = afterFileRead;
    reader.readAsText(file);

    notify("Reading ...");
}

function afterFileRead(event) {

    txtInput.value = event.target.result;

    setTimeout(function () {
        notify("Processing");
        setTimeout(parse, 500);
    }, 500);
}


function clearAll() {

    txtInput.value = EMPTY;
    txtOutput.value = EMPTY;
    txtVirtualOutput.value = EMPTY;
    fileUploadInput.value = EMPTY;

    lblResult.innerHTML = RESULT;
    lblAutogenerated.innerHTML = AUTO_GENERATED;
    fileUploadInput.value = EMPTY;

    showHideDownload();
}

function download(selector) {

    let textToDownload = document.querySelector(selector).value;

    if (textToDownload) {
        let blob = new Blob([textToDownload], { type: DOWNLOAD_FILE_TYPE });

        let downloadLink = document.createElement("a");
        downloadLink.download = `${DOWNLOAD_FILE_NAME}_${(new Date()).toISOString().replace(/z|t/gi, ' ').trim()}.txt`;
        downloadLink.innerHTML = "download";

        if (window.webkitURL != null) {
            downloadLink.href = window.webkitURL.createObjectURL(blob);
        }
        else {
            downloadLink.href = window.URL.createObjectURL(blob);
            // downloadLink.onclick = destroyClickedElement;
            downloadLink.style.display = "none";
            document.body.appendChild(downloadLink);
        }

        downloadLink.click();
    }

    notify("Download Completed");
}

function showHideDownload() {

    setVisible(btnDownload, txtOutput.value);
    setVisible(btnOutputCopy, txtOutput.value);

    setVisible(btnVirtualOutputDownload, txtVirtualOutput.value);
    setVisible(btnAutoOutputCopy, txtVirtualOutput.value);
}

function setVisible(element, condition) {
    element.style.visibility = condition ? VISIBLE : HIDDEN;
}

function copy(selector) {

    let textarea = document.querySelector(selector);
    textarea.select();
    textarea.setSelectionRange(0, 99999);
    navigator.clipboard.writeText(textarea.value);

    notify("Copied to Clipboard");
}

function notify(message) {
    notification.style.visibility = VISIBLE;
    notificationText.innerHTML = message || EMPTY;
    $(".alert").fadeTo(2000, 500).slideUp(500, function () {
        $(".alert").slideUp(500);
    });
}

function initialize() {

    txtInput = document.querySelector("#input-text");
    inputPatterns = document.querySelector("#input-patterns");
    txtOutput = document.querySelector("#output-text");
    txtVirtualOutput = document.querySelector("#auto-output-text");
    fileUploadInput = document.querySelector("#fileInput");

    btnDownload = document.querySelector("#output-download");
    btnVirtualOutputDownload = document.querySelector("#auto-output-download");

    btnOutputCopy = document.querySelector("#output-copy");
    btnAutoOutputCopy = document.querySelector("#auto-output-copy");

    btnParse = document.querySelector("#btnParse");
    btnClear = document.querySelector("#btnClear");
    lblResult = document.querySelector("#lblResult");
    lblAutogenerated = document.querySelector("#lblAutogenerated");

    notification = document.querySelector("#notification");
    notificationText = document.querySelector("#lblNotificationText");

    chkAutoGenerate = document.querySelector("#chkAutoGenerate");
    chkReplaceInput = document.querySelector("#chkReplaceNumber");

    clearAll();
}



// globals
let txtInput, inputPatterns, txtOutput, txtVirtualOutput,
    fileUploadInput, btnDownload, btnVirtualOutputDownload,
    btnParse, btnClear, lblResult, lblAutogenerated,
    notification, notificationText, btnOutputCopy, btnAutoOutputCopy,
    chkAutoGenerate, chkReplaceInput;


const RESULT = "Result",
    AUTO_GENERATED = "Autogenerated",
    EMPTY = "",
    VISIBLE = "visible",
    HIDDEN = "hidden",
    CR_LF = "\r\n",
    DOWNLOAD_FILE_TYPE = "text/plain",
    DOWNLOAD_FILE_NAME = "Numbers";