/*
 * Copyright 2022 Liju Jayakumar. All Rights Reserved.
*/

/*jshint esversion: 6 */

// globals
let txtInput, inputPatterns, txtOutput, txtVirtualOutput,
    fileUploadInput, btnDownload, btnVirtualOutputDownload,
    btnParse, btnClear, lblResult, lblAutogenerated,
    notification, notificationText, btnOutputCopy, btnAutoOutputCopy,
    chkAutoGenerate, chkReplaceInput, txtIdentifier;



const RESULT = "Result",
    AUTO_GENERATED = "Autogenerated",
    EMPTY = "",
    VISIBLE = "visible",
    HIDDEN = "hidden",
    CR_LF = "\r\n",
    DOWNLOAD_FILE_TYPE = "text/plain",
    DOWNLOAD_FILE_NAME = "Numbers",
    SPACE = " ",
    TAB = "\t";